on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: onlinerestaurantnewacs.azurecr.io
        username: ${{ secrets.acr_onlinerestaurantnewacs_username }}
        password: ${{ secrets.acr_onlinerestaurantnewacs_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/RestaurantAPI" -f  "RestaurantAPI/Dockerfile" -t onlinerestaurantnewacs.azurecr.io/onlinerestaurantaks:${{ github.sha }} --label dockerfile-path=RestaurantAPI/Dockerfile
        docker push onlinerestaurantnewacs.azurecr.io/onlinerestaurantaks:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_onlinerestaurantaks_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep onlinerestaurantaks9e62 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace onlinerestaurantaks9e62`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: onlinerestaurantaks9e62
        container-registry-url: onlinerestaurantnewacs.azurecr.io
        container-registry-username: ${{ secrets.acr_onlinerestaurantnewacs_username }}
        container-registry-password: ${{ secrets.acr_onlinerestaurantnewacs_password }}
        secret-name: onlinerestaudockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: onlinerestaurantaks9e62
        manifests: |
          manifests/deployment-1.yml
          manifests/service-1.yml
        images: |
          onlinerestaurantnewacs.azurecr.io/onlinerestaurantaks:${{ github.sha }}
        imagepullsecrets: |
          onlinerestaudockerauth
